### PR TITLE
Fixes badmatch in bank_server

### PR DESCRIPTION
**Pull request by ghost**
When calling bank:start_pool/3 with the same Ref after bank:stop_pool/1 has been called, bank_server will crash with a badmatch.

### CODE REVIEW

**Comment by essen** [comment]
There's a dialyzer error:

```
bank.erl:46: Expression produces a value of type 'ok' | {'error','not_found' | 'restarting' | 'running' | 'simple_one_for_one'}, but this value is unmatched
```

**Comment by ghost** [comment]
Now it passes.

**Comment by essen** [comment]
I just realized the indentation is completely messed up. Hope it was OK in the previous merges. Please fix it here.

Also why not just invert the calling order?

**Comment by ghost** [comment]
It was my IDE which caused this mess. Sorry! Previous merges seem to be okay.

**Comment by essen** [comment]
Merged, thanks! Keep it up!

**Pull request merged**
